### PR TITLE
feat: Ability to create folders in a file function

### PR DESCRIPTION
**Pull request by cothi**
Hello!, I'm using the sidebar well

## Feature Proposal

Previously, the function only supported file creation. But sometimes when you're working, you have to create folders and create files together create files. For more convenience, **I added a folder function. If you don't mind, why don't you add a function?**

## record
test_record

thx

### CODE REVIEW

**Review by GustavoKatel — COMMENTED** [review]
hi! I think this a good idea, but the implementation is a bit more complicated then it needs to be.

I think we can reduce the complexity by a lot if we do something like this:

```lua
local parent_folders = vim.fn.fnamemodify(dest, ":h")
vim.fn.mkdir(parent_folders, "p")
```

what do you think?

**Comment by cothi** [comment]
I think the proposed code is clean!
I uploaded the code again with the suggested code, is this right?

https://github.com/sidebar-nvim/sidebar.nvim/pull/83/commits/3202d598a9745b07e978f61070971c92757f98fc

**Comment by GustavoKatel** [comment]
if I'm understanding the code correctly, then I think the whole `for` loop and the helper functions can be replaced with a single `vim.fn.mkdir(parent_folders, "p")` 

the second parameter `p` tells the function to also create intermediate folders

**Comment by cothi** [comment]
I was missing the mkdir option -p.

**Comment by GustavoKatel** [comment]
thanks @cothi ! this looks great

**Pull request merged**
